name: Primer workflow

on: push

jobs:
  wallet:
    runs-on: ubuntu-latest

    steps:
      - name: Bajar codigo
        uses: actions/checkout@v4
      - name: Instalar pytest
        run: pip install pytest
      - name: Probar codigo
        run: pytest test.py
      - name: Crear una imagen Docker
        run: docker build -t jonmm021/holamundo .
      - name: Probar contenedor
        run: docker run jonmm021/holamundo
